### ISSUE TITLE
ambiguous tables handled differently in markdown-it-py and mdformat

### ISSUE THREAD

**Issue by inktrap** [executablebooks/mdformat-tables#15]
### Describe the bug/feature

**Edit:** [fixtures.md](https://raw.githubusercontent.com/executablebooks/mdformat-tables/master/tests/fixtures.md) says: "A list takes precedence in case of ambiguity" … so maybe the example document of markdown-it-py should be changed if this is not a bug, but a feature? (And this is example is literally included as a fixture!) However, … I kind of expect the things mardown-it-py and mdformat can do to be the same, if I am using `MDRenderer`. So because of that I would leave this issue open.

**context**
When I call mdformat with mdformat-tables installed and try to re-format the table of the example document, the table is not displayed correctly, while your example works.

**expectation**
Table from here: <https://github.com/executablebooks/markdown-it-py#python-api-usage=>

```
## Tables

This should be a table:

a | b
- | -
1 | 2

This is another table:

a | b | c
:- | -: | :-:
1 | 2 | 3
xxxxxx | yyyyyy | zzzzzz

That should work with mdformat.
```

I expected the output to be maybe something like this:

```
## Tables

This should be a table:

  a   |   b
----- | ----
  1   |   2

This is another table:

| a      |      b |   c    |
| :----- | -----: | :----: |
| 1      |      2 |   3    |
| xxxxxx | yyyyyy | zzzzzz |

That should work with mdformat.
```

**bug**

But instead this is the output:

```
## Tables

This should be a table:

a | b

- | \-
  1 | 2

This is another table:

| a      |      b |   c    |
| :----- | -----: | :----: |
| 1      |      2 |   3    |
| xxxxxx | yyyyyy | zzzzzz |

That should work with mdformat.

```

### Reproduce the bug

Use the provided example documents to reproduce the output.

### List your environment

beautysh             6.2.1
black                22.6.0
click                8.1.3
colorama             0.4.5
linkify-it-py        1.0.3
markdown-it-py       2.1.0
mdformat             0.7.14
mdformat-beautysh    0.1.1
mdformat-black       0.1.1
mdformat-config      0.1.3
mdformat_footnote    0.1.1
mdformat_frontmatter 0.4.1
mdformat-shfmt       0.1.0
mdformat_tables      0.4.1
mdformat-toc         0.3.0
mdit-py-plugins      0.3.0
mdurl                0.1.1
mypy-extensions      0.4.3
pathspec             0.9.0
pip                  22.1.1
platformdirs         2.5.2
ruamel.yaml          0.17.21
ruamel.yaml.clib     0.2.6
setuptools           59.6.0
toml                 0.10.2
tomli                2.0.1
types-colorama       0.4.14
types-setuptools     57.4.18
uc-micro-py          1.0.1

**Comment by hukkin** [comment]
Thanks for the issue!

This is not a bug. The following is not a table in GFM

```markdown
a | b
- | -
1 | 2
```

It'd be good to fix the example in markdown-it-py. Do you want to make a PR adding leading and trailing pipe characters?
