### ISSUE TITLE
Treat two-width character incorrectly

### ISSUE THREAD

**Issue by Freed-Wu** [executablebooks/mdformat-tables#16]
### Describe the bug

**context**
```
| 模型    | 时间    |
|---------|---------|
| BBFN    | 2021-07 |
```

**expectation**

```
| 模型    | 时间    |
| ------- | ------- |
| BBFN    | 2021-07 |
```

**bug**
```
| 模型      | 时间      |
| ------- | ------- |
| BBFN    | 2021-07 |
```
![Screenshot from 2022-09-19 22-46-03](https://user-images.githubusercontent.com/32936898/191045590-06a6090e-c69f-4f44-9dff-9e25a336f67b.png)

**problem**
Asian characters have double width.

### Reproduce the bug

`mdformat` a table containing Asian characters.

```
| 模型    | 时间    |
|---------|---------|
| BBFN    | 2021-07 |
```

**Comment by hukkin** [comment]
Thanks for the issue!

I moved this to mdformat-tables issue tracker as mdformat core does not format tables.

Is there a database/mapping somewhere that shows the width of Unicode characters? If the width is font dependent, I'd be inclined to perhaps stick to current style where each Unicode character is considered to have the same width.

**Comment by Freed-Wu** [comment]
> Is there a database/mapping somewhere that shows the width of Unicode characters?

<https://github.com/jquast/wcwidth> should be your need.

**Comment by Freed-Wu** [comment]
Any progress about this issue?

**Comment by KyleKing** [comment]
FYI, I'm taking a look at: https://github.com/hukkin/mdformat-gfm/issues/33

And might be able to help make this change in parallel

**Comment by KyleKing** [comment]
I have a PR ready, pending the other changes I have open: https://github.com/KyleKing/mdformat-tables/pull/1

Hopefully the patch should be released in the next few weeks if still useful to you 🤞🏻
