### ISSUE TITLE
mdformat-tables incompatible with mdformat 0.5.3 ?

### ISSUE THREAD

**Issue by malacoss** [executablebooks/mdformat-tables#4]
**Describe the bug**
Installing `mdformat-tables` downgrades `mdtables` to `0.3.5`.

**To Reproduce**

1. pip  install mdformat==0.5.3
2. pip  install mdformat-tables

**Expected behavior**

Only package `mdformat-tables` should be installed.

```
pip  install mdformat-tables
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting mdformat-tables
  Downloading mdformat_tables-0.2.0-py3-none-any.whl (4.7 kB)
Collecting mdformat~=0.3.2
  Downloading mdformat-0.3.5-py3-none-any.whl (18 kB)
Requirement already satisfied: markdown-it-py<0.6.0,>=0.5.5 in /usr/local/lib/python3.9/site-packages (from mdformat~=0.3.2->mdformat-tables) (0.5.6)
Requirement already satisfied: attrs<21,>=19 in /usr/lib/python3.9/site-packages (from markdown-it-py<0.6.0,>=0.5.5->mdformat~=0.3.2->mdformat-tables) (19.3.0)
Installing collected packages: mdformat, mdformat-tables
  Attempting uninstall: mdformat
    Found existing installation: mdformat 0.5.3
    Uninstalling mdformat-0.5.3:
      Successfully uninstalled mdformat-0.5.3
Successfully installed mdformat-0.3.5 mdformat-tables-0.2.0
```

**Environment**

- Python 3.9.0
- Operating System: Fedora 31

thanks

**Comment by chrisjsewell** [comment]
Heya, this is not a bug its just how pip works, the latest release of mdformat-tables is not specified to be compatible with the that version of mdformat.
If you want to ignore dependencies, you can use: `pip install --no-deps mdformat-table`

Anyhow I'll release a new version now 😄

**Comment by malacoss** [comment]
Thanks @chrisjsewell
